#!/usr/bin/env python3
"""Compute subject-level fixed effects from run-wise contrast maps.

The script expects run-level effect-size and effect-variance maps generated by a
first-level GLM and combines them into a single fixed-effects map per subject and
contrast.
"""
from __future__ import annotations

import argparse
from pathlib import Path
import logging
from nilearn.glm.contrasts import compute_fixed_effects

LOGGER = logging.getLogger("fixed_effects_from_runs")


def configure_logging(verbose: bool = False) -> None:
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(level=level, format="[%(levelname)s] %(message)s")


def build_file_list(input_dir: Path, subject: str, contrast: str, suffix: str) -> list[str]:
    pattern = f"{subject}*{contrast}_{suffix}.nii.gz"
    return sorted(str(p) for p in input_dir.glob(pattern))


def run_fixed_effects(input_dir: Path, output_dir: Path, subject: str, contrast: str, mask: str | None = None) -> None:
    effect_size = build_file_list(input_dir, subject, contrast, "effectsize")
    effect_variance = build_file_list(input_dir, subject, contrast, "effectvariance")
    if len(effect_size) == 0 or len(effect_variance) == 0:
        raise FileNotFoundError(f"No run-wise maps found for {subject} / {contrast}")
    if len(effect_size) != len(effect_variance):
        raise ValueError("Effect-size and effect-variance counts do not match")

    fixed_fx, fixed_var, fixed_z = compute_fixed_effects(effect_size, effect_variance, mask=mask)
    output_dir.mkdir(parents=True, exist_ok=True)
    fixed_fx.to_filename(output_dir / f"{subject}_{contrast}_fixedfx_effect.nii.gz")
    fixed_var.to_filename(output_dir / f"{subject}_{contrast}_fixedfx_variance.nii.gz")
    fixed_z.to_filename(output_dir / f"{subject}_{contrast}_fixedfx_zscore.nii.gz")
    LOGGER.info("Wrote fixed effects for %s / %s", subject, contrast)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--subject", required=True)
    parser.add_argument("--contrast", required=True)
    parser.add_argument("--mask")
    parser.add_argument("--verbose", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    configure_logging(args.verbose)
    run_fixed_effects(args.input_dir, args.output_dir, args.subject, args.contrast, args.mask)


if __name__ == "__main__":
    main()
